### ISSUE TITLE
Src

### ISSUE THREAD

**Issue by SeaUrgin** [lamzvam/verus-anticheat#1]
Where is src? When I open the zip file, all I see is readme

**Comment by Giacomo213342** [comment]
this is likely a rat xd

**Comment by lamzvam** [comment]
> Where is src? When I open the zip file, all I see is readme

the src atm isnt released

**Comment by lamzvam** [comment]
> this is likely a rat xd

omg! you can run the jar anywhere and see if its doing something weird

**Comment by Giacomo213342** [comment]
> > this is likely a rat xd
> 
> omg! you can run the jar anywhere and see if its doing something weird

you know, I have seen many rats working like that. If you say "it is now open source" and don't attach any source code you release the plugin in releases then I think it's a rat.

**Comment by lamzvam** [comment]
> > > this is likely a rat xd
> > 
> > 
> > omg! you can run the jar anywhere and see if its doing something weird
> 
> you know, I have seen many rats working like that. If you say "it is now open source" and don't attach any source code you release the plugin in releases then I think it's a rat.

"many rats working like that" , what? you also can check the plugin doesnt connect to the net or do something weird. The src will be released only if verus dmca this repo

**Comment by lamzvam** [comment]
> > > > > this is likely a rat xd
> > > > 
> > > > 
> > > > omg! you can run the jar anywhere and see if its doing something weird
> > > 
> > > 
> > > you know, I have seen many rats working like that. If you say "it is now open source" and don't attach any source code you release the plugin in releases then I think it's a rat.
> > 
> > 
> > "many rats working like that" , what? you also can check the plugin doesnt connect to the net or do something weird. The src will be released only if verus dmca this repo
> 
> Sorry for supposing this was a rat just because some rats use github releases. Maybe you could write that you would release the src in another moment. May I ask why it is obfuscated even tho you have its src? It's just to know, im not accusing you of anything.

i released the jar obfuscated bc if i did that with no obfuscation is same to release the src , it will be released as soon as verus dmca this repo
